bounds:
  syn_weight: !!python/tuple
  - 1.0E-8
  - 10.
feature_names:
- EPSP
features_modules: !!python/tuple
- pc_simple_network_submodule
get_features: !!python/tuple
- get_EPSP_features
kwargs:
  mech_file_path: data/090717 GC optimizing spiking.yaml
  neuroH5_file_path: morphologies/121516_DGC_trees.pkl
  neuroH5_index: 0
  spines: False
  cvode: False
  verbose: False
  daspk: True
objective_names:
- EPSP
objectives_modules: !!python/tuple
- pc_simple_network_submodule
optimization_title: simple_ring
param_gen: BGen
param_names:
- syn_weight
subworld_size: 2
target_range:
  EPSP: 4.
target_val:
  EPSP: 10.
update_params: !!python/tuple
- update_pas_exp
update_modules: !!python/tuple
- parallel_optimize_GC_leak
x0:
  syn_weight: 0.01