bounds:
  AMPA.tau: !!python/tuple
  - 50.
  - 400.
  AMPA.slope: !!python/tuple
  - 1.0e-7
  - 0.01
  AMPA.g0: !!python/tuple
  - 1.0e-4
  - 0.01
  AMPA.gmax bo: !!python/tuple
  - 4
  - 6
  NMDA.gmax: !!python/tuple
  - 1.0e-4
  - 5.0e-3
  NMDA.gamma: !!python/tuple
  - 0.05
  - 0.12
  NMDA.Kd: !!python/tuple
  - 3.
  - 10.
  NMDA.kin_scale: !!python/tuple
  - 1.
  - 4.
  soma.gbar_nas: !!python/tuple
  - 0.01
  - 0.05
  dend.gbar_nas: !!python/tuple
  - 0.01
  - 0.05
  dend.gbar_nas slope: !!python/tuple
  - -0.0004
  - 0.
  dend.gbar_nas min: !!python/tuple
  - 0.
  - 0.03
  dend.gbar_nas bo: !!python/tuple
  - 2
  - 6
  soma.gkabar: !!python/tuple
  - 0.01
  - 0.05
  dend.gkabar: !!python/tuple
  - 0.01
  - 0.25
default_params:
  soma.gbar_nas: 0.030821815154669967
  soma.gkabar: 0.033171536167129576
feature_names:
- dend_AP_amp
- soma_EPSP_amp
- NMDA_contribution
- integration_gain_control
- integration_gain_AP5
- initial_gain_AP5
- initial_gain_control
features_modules: !!python/tuple
- parallel_optimize_synaptic_integration
#- parallel_optimize_synaptic_integration
#- parallel_optimize_synaptic_integration
get_features: !!python/tuple
- get_unitary_EPSP_features
#- get_compound_EPSP_features
#- get_stability_features
group_sizes: !!python/tuple
- 28
- 80
- 1
kwargs:
  mech_file_path: data/090717 GC optimizing synaptic.yaml
  neuroH5_file_path: morphologies/121516_DGC_trees.pkl
  neuroH5_index: 0
  spines: False
  verbose: True
  cvode: False
  daspk: True
objective_names:
- dend_AP_amp
- soma_EPSP_amp
- NMDA_contribution
- integration_gain_control
- integration_gain_AP5
- initial_gain_AP5
- initial_gain_control
objectives_modules: !!python/tuple
- parallel_optimize_synaptic_integration
optimization_title: synaptic
param_gen: BGen
param_names:
- AMPA.tau
- AMPA.slope
- AMPA.g0
- AMPA.gmax bo
- NMDA.gmax
- NMDA.gamma
- NMDA.Kd
- NMDA.kin_scale
- soma.gbar_nas
- dend.gbar_nas
- dend.gbar_nas slope
- dend.gbar_nas min
- dend.gbar_nas bo
- soma.gkabar
- dend.gkabar
rel_bounds:
- - dend.gbar_nas min
  - '<'
  - 1.0
  - soma.gbar_nas
- - dend.gbar_nas
  - <
  - 1.0
  - soma.gbar_nas
- - dend.gbar_nas
  - '>'
  - 1.0
  - dend.gbar_nas min
target_range:
  dend_AP_amp: 0.005
  soma_EPSP_amp: 0.01
  NMDA_contribution: 0.05
  integration_gain_control: 0.05
  integration_gain_AP5: 0.05
  initial_gain_AP5: 0.1
  initial_gain_control: 0.1
target_val:
  dend_AP_amp: 0.3
  soma_EPSP_amp: 0.5
  NMDA_contribution: 0.
  integration_gain_control: 1.38
  integration_gain_AP5: 0.8
  initial_gain_AP5: 0.
  initial_gain_control: 0.
update_params: !!python/tuple
- update_AMPA_NMDA
update_modules: !!python/tuple
- parallel_optimize_synaptic_integration
x0:
  AMPA.tau: 7.90793466e+01
  AMPA.slope: 6.65158925e-05
  AMPA.g0: 1.71052379e-03
  AMPA.gmax bo: 5
  NMDA.gmax: 3.613E-03
  NMDA.gamma: 0.100
  NMDA.Kd: 7.51
  NMDA.kin_scale: 1.81
  soma.gbar_nas: 0.030821815154669967
  dend.gbar_nas: 0.03
  dend.gbar_nas slope: -0.0001
  dend.gbar_nas min: 0.
  dend.gbar_nas bo: 5
  soma.gkabar: 0.033171536167129576
  dend.gkabar: 0.05
